### PR TITLE
adding the option to build a pca on only filtered data

### PR DESCRIPTION
**Pull request by cmaceves**

### CODE REVIEW

**Comment by mwang87** [comment]
I think one issue we might get is if two people come to the website at the same time, they might write over each other's index.html.

**Comment by cmaceves** [comment]
@mwang87 added a random number to the location to help avoid that

**Comment by mwang87** [comment]
Can you use str(uuid.uuid4()) this is assumed to be a better randomization scheme than simply random.

**Comment by cmaceves** [comment]
@mwang87 made the change requested

**Comment by mwang87** [comment]
Awesome, looks good. merging.

**Pull request merged**
