### PR TITLE
Marine Nudibranch

### PR DESCRIPTION
**Pull request by viqqikurnianda**
The content for NCBI Taxonomy

### CODE REVIEW

**Comment by alan-jarmusch** [comment]
Hi @viqqikurnianda - are you requesting that the following be added as options?Phyllidiella pustulosa
Phyllidiella aff. nigra
Phyllidiella krempfi
Phyllidiella sp1.
Phyllidiella sp2.

**Comment by alan-jarmusch** [comment]
@viqqikurnianda  I was able to find 

- 154616|Phyllidiella pustulosa
- 1881994|Phyllidiella nigra (Is this = to Phyllidiella aff. nigra?)
- I cannot find an NCBI taxonomy ID for this Phyllidiella krempfi - can you provide? If not, then we will proceed without one.
- 154615|Phyllidiella (this can is the NCBI taxonomy ID for the genus and can be used for your species 1 and 2)

**Comment by viqqikurnianda** [comment]
﻿Dear,

Thank you for the information.

I would like to confirm that:

1881994|Phyllidiella nigra
Yes, It is refer to Phyllidiella aff. nigra.

154615|Phyllidiella
Yes, I agree with you. It can be used for the species 1 and 2.

For Phyllidiella krempfi, I could not found any information. We can skip for this species.

Would you please process for (a) 154616|Phyllidiella pustulosa, (b) 1881994|Phyllidiella nigra, and (c) 154615|Phyllidiella.

Thank you for the helps.

Regards,

Viqqi

**Comment by viqqikurnianda** [comment]
Dear Mr.,

Thank you for updating the NCBI Taxonomy in ReDU.
However, I could not pass the ReDU validator when I choose 154616|Phyllidiella pustulosa as the NCBI Taxonomy.
Moreover, when I choose another species such as 70919|Sarcophyton glaucum, it would passed the ReDU validator.

Would you please to help me for this condition?

Also, I present the template as proof.

Regards,

Viqqi

**Comment by alan-jarmusch** [comment]
hi @viqqikurnianda, great. I have added those species to the template (as I think you have discovered). The reason that the file failed to validate - I had not pushed an update to the validator as I'm just now getting to the response. I'll submit the update now and the validator will be updated with the next release. For now, you can proceed with uploading to massive if the only errors were related to the taxonomy. If you don't see your data appear in the file selector in the next couple of days please follow up with me. I apologize for the delay in updating - things are a bit slower than normal.

**Comment by viqqikurnianda** [comment]
Dear Mr.,

Thank you for the email.

It work. 

Thank you for the helps.

Regards,

Viqqi

**Pull request closed without merging**
